//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADONetExam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancy
    {
        public int Id { get; set; }
        public string NameVacancy { get; set; }
        public string URLVacancy { get; set; }
        public string DescriptionVacancy { get; set; }
        public System.DateTime DatePublicationVacancy { get; set; }
        public string EmailAuthorVacancy { get; set; }
    }
}
